### ISSUE TITLE
In report, add value used as offset in `Correction offseted inverse value`

### ISSUE THREAD

**Issue by wiesnim9** [Argmaster/CSSFinder#49]

**Comment by Argmaster** [comment]
Feature implemented on development branch with b04ba3f274a750b976be5fb38ef448466e452895

**Comment by Argmaster** [comment]
Released in [0.7.0](https://pypi.org/project/cssfinder/0.7.0/)  (77bc81369c863c4b29517cd90dd2a31f77ae125d)
