### ISSUE TITLE
Add command for listing tasks in project

### ISSUE THREAD

**Issue by wiesnim9** [Argmaster/CSSFinder#51]

**Comment by Argmaster** [comment]
Implemented on dev branch with 0f5f60a8ab54462cc597d11897186be8d2282a9b "Add command for inspecting projects"

**Comment by Argmaster** [comment]
Released in [0.7.0](https://pypi.org/project/cssfinder/0.7.0/)  (77bc81369c863c4b29517cd90dd2a31f77ae125d)
