### ISSUE TITLE
Remolve -p flag in favour of selecting project from cwd

### ISSUE THREAD

**Issue by wiesnim9** [Argmaster/CSSFinder#54]
It will require user to move into project directory.

**Comment by Argmaster** [comment]
Implemented on dev branch with ff69062008bd4505b7657f10c90c0190560c05e8 "Flatten command line interface"

**Comment by Argmaster** [comment]
Released in [0.7.0](https://pypi.org/project/cssfinder/0.7.0/)  (77bc81369c863c4b29517cd90dd2a31f77ae125d)
